### ISSUE TITLE
[Build|zlib] Build zlib as static library

### ISSUE THREAD

**Issue by DronCode** [DronCode/libzip#1]
## TODO
Under Windows we have trouble with linking zlib. 
We should compile zlib as static library too.
- [ ] Build zlib as static library
- [ ] Check it under Linux
- [ ] Check it under Windows
- [ ] Check it under MacOS

**Comment by DronCode** [comment]
**Commit:** 76682fc
Fixed
